Repository snakemake/snakemake, pull requests merged in 2025-03, with the labels that each got.

#3369 feat: Modernize package configuration using Pixi
  .gitattributes
  .github/workflows/main.yml
  .gitignore
  pyproject.toml
  setup.cfg
  snakemake/template_rendering/yte.py
  tests/tests.py
  tests/tests_using_conda.py
Labels: enhancement, hackathon-2025

#3265 fix: `--delete-all-output` ignores `--dry-run`
  src/snakemake/cli.py
  tests/test_delete_all_output/Snakefile
  tests/test_github_issue_3265_respect_dryrun_delete_all/Snakefile
  tests/test_github_issue_3265_respect_dryrun_delete_all/Snakefile_inner
  tests/test_github_issue_3265_respect_dryrun_delete_all/expected-results/all_ok
  tests/test_github_issue_3265_respect_dryrun_delete_all/infile
  tests/tests.py
Labels: bug

#3415 docs: Updating contributing guidelines with new pixi dev setup
  .github/workflows/docs.yml
  docs/project_info/contributing.rst
  pyproject.toml
Labels: documentation

#3419 fix: ReadTheDocs layout issue due to src directory change
  apidocs/conf.py
  docs/conf.py
Labels: bug

#3378 feat: optionally auto-group jobs via temp files in case of remote execution
  docs/snakefiles/rules.rst
  src/snakemake/dag.py
  src/snakemake/io.py
  src/snakemake/jobs.py
  src/snakemake/rules.py
  tests/test_nodelocal/Snakefile
  tests/test_nodelocal/expected-results/local/local
  tests/test_nodelocal/expected-results/local/persist.txt
  tests/test_nodelocal/expected-results/results/result.txt
  tests/test_nodelocal/qsub
  tests/test_nodelocal/qsub_stage2
  tests/tests.py
Labels: enhancement, hackathon-2025

#3417 test: Add pytest markers & skips, update docs to reflect changes
  .github/workflows/main.yml
  .test_durations
  docs/project_info/contributing.rst
  pyproject.toml
  tests/conftest.py
  tests/tests.py
Labels: documentation

#3386 feat: Enable saving and reloading IOCache object
  src/snakemake/cli.py
  src/snakemake/dag.py
  src/snakemake/io.py
  src/snakemake/persistence.py
  src/snakemake/settings/types.py
  tests/common.py
  tests/tests.py
Labels: enhancement, hackathon-2025

#3407 fix: Show apptainer image URL in snakemake report
  src/snakemake/report/html_reporter/template/components/rule_info.js
Labels: hackathon-2025

#3437 docs: update broken links documentation
  docs/project_info/codebase.rst
Labels: documentation

#3453 docs: fix profiles linking, add Sphinx rst syntax infos
  docs/executing/cli.rst
  docs/getting_started/migration.rst
  docs/project_info/contributing.rst
  docs/snakefiles/configuration.rst
  docs/snakefiles/rules.rst
Labels: documentation

#3455 test: plugins as pypi-dependencies to not depend on feedstocks
  pyproject.toml
Labels: bug
